import React from 'react';
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';

import Navbar from '@/components/home/Navbar';
import Footer from '@/components/home/Footer';


import prisma from '@/lib/prisma';
import { createClient } from '@/utils/supabase/server';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const urbanist = Urbanist({ subsets: ['latin'] });

const Layout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const supabase = createClient();
  
	const {
	  data: { user },
	  } = await supabase.auth.getUser();

	let dbUser = user
    ? await prisma.user.findUnique({
        where: { id: user.id },
        select: { avatar_url: true },
      })
    : null;

	const isAdmin = user?.email === process.env.ADMIN_EMAIL;

	const avatarUrl = dbUser?.avatar_url || user?.user_metadata?.avatar_url;
	
	const lists = await prisma.category.findMany({}) || [];

	return (
		<div className={urbanist.className}>
			<Navbar
				user={user}
				isAdmin={isAdmin}
				lists={lists}
				userIcon={avatarUrl}
			/>
			<main>{children}</main>
			<Footer />
		</div>
	);
};

export default Layout;