
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';

import Navbar from '@/components/home/Navbar';
import Footer from '@/components/home/Footer';
import prisma from '@/lib/prisma';
import { getUserData } from '../actions/user';
import Overlay from './ui/Overlay';

export const metadata: Metadata = {
	title: 'Smart - shop',
	description: 'Generated by create next app',
};

const urbanist = Urbanist({ subsets: ['latin'] });

const Layout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const { user, isAdmin, avatarUrl } = await getUserData();
	const lists = await prisma.category.findMany({}) || [];

	return (
		<div className={urbanist.className}>
		<Overlay/>
			<Navbar
				user={user}
				isAdmin={isAdmin}
				lists={lists}
				userIcon={avatarUrl}
			/>
			<main>{children}</main>
			<Footer />

			
		</div>
	);
};

export default Layout;