
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';

import Navbar from '@/components/home/Navbar';
import Footer from '@/components/home/Footer';
import prisma from '@/lib/prisma';
import { getUserData } from '../actions/user';

export const metadata: Metadata = {
	title: 'Smart - shop',
	description: 'Generated by create next app',
};

const urbanist = Urbanist({ subsets: ['latin'] });

const Layout = async ({
	children,
  }: Readonly<{
	children: React.ReactNode;
  }>) => {
	try {
	  const [{ user, isAdmin, avatarUrl }, lists] = await Promise.all([
		getUserData(),
		prisma.category.findMany({})
	  ]);
  
	  return (
		<div className={urbanist.className}>
		  <Navbar
			user={user}
			isAdmin={isAdmin}
			lists={lists || []}
			userIcon={avatarUrl}
		  />
		  <main>{children}</main>
		  <Footer />
		</div>
	  );
	} catch (error) {
	 
	  return (
		<div className={urbanist.className}>
		  <Navbar
			user={null}
			isAdmin={false}
			lists={[]}
			userIcon={null}
		  />
		  <main>{children}</main>
		  <Footer />
		</div>
	  );
	}
  };