/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/versace_bag.glb --typescript --draco --root group 
Author: hanish Goar (https://sketchfab.com/hanish)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/versace-bag-e0bfc49fde124fb89cd5cacb0be1a1d6
Title: Versace Bag
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Versace(props) {
  const { nodes, materials } = useGLTF('/models/versace_bag.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Gold} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Leather} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/versace_bag.glb')
